#!/usr/bin/bash
if [$(hostname) -eq "kriemhild"]
then
	# xrandr-stuff for laptop
	xrandr | grep "DP2-3 connected"
	STATUS=$?

	if [ "$STATUS" -eq "0" ]
	then
		#dock
		xrandr --output eDP1 --off --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1200 --pos 1920x0 --rotate normal --dpi 96 --output DP2-3 --mode 1920x1200 --pos 0x0 --rotate normal --dpi 96 --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --dpi 96
	else
		#no dock
		xrandr --output eDP1 --mode 1920x1080 --primary --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --dpi 96
	fi
fi

export _JAVA_AWT_WM_NONREPARENTING=1
dwm
